### ISSUE TITLE
aln format

### ISSUE THREAD

**Issue by ryan-224** [fusong-ju/ProFOLD#1]
Hi there,

Thanks for sharing your work with us.

Could you please suggest how to generate the aln format MSA that fits the model?

Thanks a lot.

**Comment by fusong-ju** [comment]
In the paper, we use [DeepMSA](https://zhanglab.dcmb.med.umich.edu/DeepMSA) to generate `aln` format file. This would work well for most query sequences. If [DeepMSA](https://zhanglab.dcmb.med.umich.edu/DeepMSA)  doesn't work for you, i.e. generates few homologue proteins, you could search against [BFD](https://bfd.mmseqs.com/) using [hhblits](https://github.com/soedinglab/hh-suite) and [MGnify](https://www.ebi.ac.uk/metagenomics/) using [HMMER](http://hmmer.org/).
