### ISSUE TITLE
how to 'Generate aln format MSA for a given target sequence' from a file in '.fasta' format?

### ISSUE THREAD

**Issue by hitsz-zuoqi** [fusong-ju/ProFOLD#2]
As depicted, I have some .fasta files which represents sequences of nucleic acid, like:

>2122_1|Chains A[auth V], B[auth W], C[auth X], D[auth Y], E[auth Z]
MSEAAQTLDGWYCLHDFRTIDWSAWKTLPNEEREAAISEFLALVDQWETTESEKQGSHAVYTIVGQKADILFMILRPTLDELHEIETALNKTKLADYLLPAYSYVSVVELSNYLASGSEDPYQIPEVRRRLYPILPKTNYICFYPMDKRRQGNDNWYMLSMEQRRELMRAHGMTGRKYAGKVTQIITGSVGLDDFEWGVTLFSDDALQFKKLVYEMRFDEVSARFGEFGSFFVGTRLPMENVSSFFHV

how can I prepare the input ? or can I directly use the fasta as input? Any idea?

**Comment by fusong-ju** [comment]
Duplicate of #1
